# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Android
    displayName: 'Android'
    pool:
      vmImage: 'windows-2019'
  
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: 6.x
        includePreviewVersions: true
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'where dotnet'
        
    - task: VSBuild@1
      inputs:
        solution: '**\*.sln'
        restoreNugetPackages: true